mus-player/account/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout/', views.logoutView, name='logout')
]

mus-player/music/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('song.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mus-player/song/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'song'

urlpatterns = [
    path('<int:pk>/', views.index, name='index'),
]

mus-player/account/models.py
from django.db import models

# Create your models here.

mus-player/song/models.py
from django.db import models

# Create your models here.
class Song(models.Model):
    title = models.CharField(max_length=255)
    artist = models.CharField(max_length=255)
    album = models.CharField(max_length=255, blank=True, null=True)
    genre = models.CharField(max_length=255)
    year = models.IntegerField(blank=True, null=True)
    lyrics = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='upload/%Y/%m/%d')
    audio_file = models.FileField(upload_to='upload/%Y/%m/%d')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
      return self.title

mus-player/account/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib import messages, auth
from django.contrib.auth import logout
from django.contrib.auth.models import User

# Create your views here.
def login(request):
    if request.user.is_authenticated:
        return redirect('song:index', pk=1)
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            messages.success(request, 'You are now logged in')
            return HttpResponseRedirect('/1/')
        else:
            messages.error(request, 'Invalid credentials')
            return HttpResponseRedirect('/account/login')
    else:
        return render(request, 'account/login.html')

def register(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/1/')
    if request.method == 'POST':
        # Get form values
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']

        # Check if passwords match
        if password == password2:
        # Check username
            if User.objects.filter(username=username).exists():
                messages.error(request, 'That username is taken')
                return HttpResponseRedirect('/account/register')
            else:
                if User.objects.filter(email=email).exists():
                    messages.error(request, 'That email is being used')
                    return HttpResponseRedirect('/account/register')
                else:
                    # Looks good
                    user = User.objects.create_user(username=username, password=password,email=email)
                    # Login after register
                    auth.login(request, user)
                    messages.success(request, 'You are now logged in')
                    return HttpResponseRedirect('/1/')
                    
        else:
            messages.error(request, 'Passwords do not match')
            return HttpResponseRedirect('/account/register')
    else:
        return render(request, 'account/register.html')


def logoutView(request):
    messages.success(request, 'You are now logged out!')
    logout(request)
    return HttpResponseRedirect('/account/login')

mus-player/song/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from .models import Song

@login_required
def index(request, pk=None):
  context = {}
  songs = Song.objects.all()
  song = Song.objects.get(id=pk)
  
  context['songs'] = songs
  context['song'] = song

  return render(request, 'song/index.html', context)

mus-player/song/templates/song/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
  <div class="container mt-5">
    <div class="card mx-auto" style="width: 24rem;">
      <div class="card-header bg-dark text-white">
        Currently Playing
      </div>
      <div class="card-body text-center bg-dark text-white">
        <img src="{{song.image.url}}" width="200px" height="200px" class="mb-2" alt="" />
        <h5 class="card-title">{{ song.title }}</h5>
        <p class="card-text">{{ song.artist }}</p>
        
        <audio controls>
          <source src="{{song.audio_file.url}}" />
          Your browser does not support the audio element.
        </audio>
      </div>
    </div>
  </div>

  <div class="container mt-5 ">
    <h3>Recommended Songs</h3>
    <ol class="list-group list-group-numbered text-white">
      <li class="list-group-item d-flex justify-content-between align-items-start bg-dark text-white">
        <div class="ms-2 me-auto">
          <div class="fw-bold">Stairway To Heaven</div>
          Led Zeppelin
        </div>
      </li class="bg-dark text-white">
      <li class="list-group-item d-flex justify-content-between align-items-start bg-dark text-white">
        <div class="ms-2 me-auto">
          <div class="fw-bold">Subheading</div>
          Content for list item
        </div>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-start bg-dark text-white">
        <div class="ms-2 me-auto">
          <div class="fw-bold">Subheading</div>
          Content for list item
        </div>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-start bg-dark text-white">
        <div class="ms-2 me-auto">
          <div class="fw-bold">Subheading</div>
          Content for list item
        </div>
      </li>
    </ol>
  </div>

  <div class="container mt-5 ">
    <h3>All Songs</h3>
    <ol class="list-group list-group-numbered text-white">
      {% for single in songs %}
      <li class="list-group-item d-flex justify-content-between align-items-start bg-dark text-white">
        <div class="ms-2 me-auto">
          <div class="fw-bold">{{ single.title }}</div>
          {{ single.artist }}
        </div>
        </li>
      {% endfor %}
      
    </ol>
  </div>
{% endblock %}

mus-player/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Music Player</title>
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
  <style>
    .full-height {
      min-height: 80vh;
    }
  </style>
<body>
  {% include 'partials/_header.html' %}

  <div class="full-height">
    {% block content %} {% endblock %}
  </div>
  
  {% include 'partials/_footer.html' %}
  
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

mus-player/templates/partials/_footer.html
<footer class="bg-dark text-white mt-5 p-5 text-center">
  Copyright &copy; All Rights Reserved.
</footer>

mus-player/templates/partials/_header.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Music Player</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">All Songs</a>
        </li>
      </ul>
      {% if not request.user.is_authenticated %}
      <ul class="navbar-nav">
        <a href="{% url 'account:login' %}" class="btn btn-secondary btn-sm me-2">Login</a>
        <a href="{% url 'account:register' %}" class="btn btn-outline-secondary btn-sm">Sign Up</a>
      </ul>
      {% else %}
        <ul class="navbar-nav me-5">
          <a href="{% url 'account:logout' %}" class="btn btn-sm btn-secondary">Log Out</a>
        </ul>

      {% endif %}
    </div>
  </div>
</nav>