proj-blog/blog/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('article/<str:category>/<slug:slug>/', views.BlogView.as_view(), name='article'),
    
]

proj-blog/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proj-blog/blog/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.safestring import mark_safe
from django.urls import reverse
from datetime import datetime

from .utils import generate_unique_slug

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=55)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Blog(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, db_index=True)
    description = models.CharField(max_length=160)
    photo_main = models.ImageField(upload_to="uploads/%Y/%m/%d/")
    slug = models.SlugField(max_length=200, unique=True, editable=False)
    content = RichTextUploadingField()
    views = models.IntegerField(default=0)
    list_date = models.DateTimeField(default=datetime.now)
    is_published = models.BooleanField(default=True)

    class Meta:
        ordering = ['-list_date']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = generate_unique_slug(Blog, self.title)

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:article', kwargs={'category':self.category, 'slug':self.slug})

proj-blog/blog/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from blog.models import Blog

class IndexView(ListView):
    context_object_name = 'blogs'
    template_name = 'blog/index.html'
    paginate_by = 12

    def get_queryset(self):
        return Blog.objects.filter(is_published=True).only('title', 'category', 'photo_main', 'list_date', 'description', 'slug')


class BlogView(DetailView):
    template_name = 'blog/article.html'
    model = Blog
    context_object_name = 'article'



class SearchView(ListView):
    context_object_name = 'blogs'
    template_name = 'blog/search.html'
    paginate_by = 12

    def get_queryset(self):
        query = self.request.GET.get('q', '')
        return Blog.objects.filter(is_published=True).filter(title__icontains=query).only('title', 'category', 'photo_main', 'list_date', 'description', 'slug')

proj-blog/blog/templates/blog/article.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
  <div class="content">
    <h1>{{article.title}}</h1>
    <img
      src="{{ article.photo_main.url }}"
      alt=""
      class="my-4"
      width="100%"
      height="600px"
    />
    <p>
      {{article.content|safe}}
     </p>
  </div>
  <hr />
  <div class="recommendations mt-5">
    <h4>Recommendations</h4>
    <div class="row mb-5">
      <div class="col-md-4">
        <div class="card">
          <img
            src="https://picsum.photos/200"
            class="card-img-top"
            alt="..."
            height="250px"
          />
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">
              Some quick example text to build on the card title
              and make up the bulk of the card's content.
            </p>
            <a href="#" class="btn btn-primary">Read Article</a>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card">
          <img
            src="https://picsum.photos/200"
            class="card-img-top"
            alt="..."
            height="250px"
          />
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">
              Some quick example text to build on the card title
              and make up the bulk of the card's content.
            </p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card">
          <img
            src="https://picsum.photos/200"
            class="card-img-top"
            alt="..."
            height="250px"
          />
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">
              Some quick example text to build on the card title
              and make up the bulk of the card's content.
            </p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

proj-blog/blog/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">
  <!-- Article List -->
  <h3>All Blogs</h3>
  <div class="row mb-5">
    {% for blog in blogs %}
      <div class="col-md-4">
        <div class="card">
          <img
            src="{{blog.photo_main.url}}"
            class="card-img-top"
            alt="..."
            height="250px"
          />
          <div class="card-body">
            <h5 class="card-title">{{blog.title|truncatechars:30}}</h5>
            <p class="card-text">
              {{blog.description|truncatechars:60}}
            </p>
            <a href="{% url 'blog:article' blog.category blog.slug %}" class="btn btn-primary">Read Article</a>
          </div>
        </div>
      </div>
    {% endfor %}
    
    
  </div>
  <!-- Article List ENds -->

  {% if is_paginated %}
      <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?q={{ request.GET.q }}&page={{ page_obj.previous_page_number }}">&laquo;</a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <a class="page-link">Previous</a>
        </li>
        {% endif %}
        {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
            <li class="page-item disabled">
              <span class="page-link">{{ i }} </span>
            </li>
        {% else %}
            <li class="page-item">
              <a class="page-link" href="?q={{ request.GET.q }}&page={{ i }}">{{ i }}</a>
            </li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?q={{ request.GET.q }}&page={{ page_obj.next_page_number }}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled"><a class="page-link">Next</a></li>
        {% endif %}
      </ul>
{% endif %}
</div>

{% endblock %}

proj-blog/blog/templates/blog/search.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <div class="container">
    <!-- Article List -->
    <h3>Here are your search results:</h3>
    <div class="row mb-5">
      {% for blog in blogs %}
        <div class="col-md-4">
          <div class="card">
            <img
              src="{{blog.photo_main.url}}"
              class="card-img-top"
              alt="..."
              height="250px"
            />
            <div class="card-body">
              <h5 class="card-title">{{blog.title|truncatechars:30}}</h5>
              <p class="card-text">
                {{blog.description|truncatechars:60}}
              </p>
              <a href="{% url 'blog:article' blog.category blog.slug %}" class="btn btn-primary">Read Article</a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>

    {% if is_paginated %}
      <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?q={{ request.GET.q }}&page={{ page_obj.previous_page_number }}">&laquo;</a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <a class="page-link">Previous</a>
        </li>
        {% endif %}
        {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
            <li class="page-item disabled">
              <span class="page-link">{{ i }} </span>
            </li>
        {% else %}
            <li class="page-item">
              <a class="page-link" href="?q={{ request.GET.q }}&page={{ i }}">{{ i }}</a>
            </li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?q={{ request.GET.q }}&page={{ page_obj.next_page_number }}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled"><a class="page-link">Next</a></li>
        {% endif %}
      </ul>
{% endif %}


  </div>
{% endblock %}

proj-blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0"
    />
    <title>Document</title>
    <!-- CSS only -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
      crossorigin="anonymous"
    />
  </head>
  <body>
    {% include 'partials/_navbar.html' %} 
    
    {% block content %} {% endblock %} 
    
    {% include 'partials/_footer.html' %}
    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

proj-blog/templates/partials/_footer.html
<footer class="footer bg-light p-5 text-center mt-5">
  Copyright &copy; 2022. All Rights Reserved.
</footer>

proj-blog/templates/partials/_navbar.html
<!-- Navbar -->
<nav
class="navbar navbar-expand-lg bg-secondary navbar-dark mb-5"
>
<div class="container-fluid">
  <a class="navbar-brand" href="#">Blog Application</a>
  <button
    class="navbar-toggler"
    type="button"
    data-bs-toggle="collapse"
    data-bs-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div
    class="collapse navbar-collapse"
    id="navbarSupportedContent"
  >
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'blog:index' %}"
          >Home</a
        >
      </li>
    </ul>
    <form class="d-flex" role="search" action="{% url 'blog:search' %}">
      <input
        class="form-control me-2"
        type="search"
        placeholder="Search"
        aria-label="Search"
        name="q"
      />
      <button class="btn btn-dark" type="submit">Search</button>
    </form>
  </div>
</div>
</nav>
<!-- Navbar ends -->